# Generated by Django 6.1 on 2026-08-11 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del País')),
                ('iso_code', models.CharField(help_text='Código ISO de 2 o 3 letras (ej. VE, US, MEX)', max_length=3, unique=True, verbose_name='Código ISO')),
                ('phone_code', models.CharField(blank=True, help_text='Ej. +58, +1', max_length=10, null=True, verbose_name='Código Telefónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Moneda')),
                ('single_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre en Singular')),
                ('plural_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre en Plural')),
                ('code', models.CharField(help_text='Código de 3 letras (ej. USD, VES, EUR)', max_length=10, unique=True, verbose_name='Código de Moneda')),
                ('symbol', models.CharField(help_text='Ej. $, Bs, €', max_length=10, verbose_name='Símbolo')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activa?')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Tasa de Cambio')),
                ('date', models.DateField(verbose_name='Fecha de la Tasa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='records.currency', verbose_name='Moneda Base')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rates', to='records.currency', verbose_name='Moneda Destino')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-date'],
                'unique_together': {('base_currency', 'target_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Estado/Provincia')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='records.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['country__name', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
