# Generated by Django 6.0 on 2026-06-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='Código de 3 letras (ej. USD, VES, EUR)', max_length=10, unique=True, verbose_name='Código de Moneda'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Tasa de Cambio'),
        ),
    ]
