# Generated by Django 6.0 on 2026-06-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_currency_code_alter_exchangerate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='plural_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre en Plural'),
        ),
        migrations.AddField(
            model_name='currency',
            name='single_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre en Singular'),
        ),
    ]
