# Generated by Django 6.1 on 2026-08-11 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Unidades, Volumen, Longitud', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VarianteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_unidad', models.PositiveIntegerField(choices=[(0, 'Unidad de Referencia'), (1, 'Menor que la unidad de referencia'), (2, 'Mayor que la unidad de referencia')], default=2)),
                ('presentacion', models.CharField(max_length=30)),
                ('cantidad_por_presentacion', models.DecimalField(decimal_places=8, max_digits=16)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='catalog.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_presentacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='catalog.producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad_presentacion', to='catalog.unidaddetalle')),
            ],
        ),
        migrations.CreateModel(
            name='VarianteGrupoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=30)),
                ('identificador', models.CharField(blank=True, max_length=30, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='catalog.variantegrupo')),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalog.producto')),
                ('variante', models.ManyToManyField(blank=True, related_name='variantes', to='catalog.variantegrupovalor')),
            ],
        ),
    ]
